// Icon set powered by lucide-react. We re-export the icons under the app's own
// names so pages can keep importing { IconBag, IconSearch, ... } unchanged.
export {
  LayoutDashboard as IconDashboard,
  Upload as IconImport,
  Package as IconInventory,
  Bell as IconAlerts,
  Clock as IconJobs,
  Globe as IconGlobe,
  ShoppingBag as IconBag,
  AlertTriangle as IconWarning,
  RefreshCw as IconRefresh,
  Eye as IconInspect,
  Info as IconInfo,
  UploadCloud as IconCloudUpload,
  FileText as IconFile,
  Sparkles as IconSparkle,
  HelpCircle as IconQuestion,
  CheckCircle2 as IconCheckCircle,
  AlertCircle as IconAlertCircle,
  Cpu as IconChip,
  Bell as IconBell,
  Search as IconSearch,
  ChevronRight as IconChevronRight,
  XCircle as IconXFail,
} from "lucide-react";
